# Generated by Django 5.2.5 on 2025-08-15 13:58

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for the user profile', primary_key=True, serialize=False)),
                ('rank', models.CharField(help_text="User's rank or position in organization", max_length=100)),
                ('unitname', models.CharField(help_text='Name of the unit or department', max_length=200)),
                ('designation', models.CharField(help_text="User's job designation or title", max_length=200)),
                ('mobileNo', models.CharField(help_text='Mobile phone number with country code', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('personalNo', models.CharField(help_text='Personal phone number with country code', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('phoneNo', models.CharField(help_text='Office or landline phone number', max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('status', models.BooleanField(default=True, help_text='Active status of the user profile')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when profile was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when profile was last updated')),
                ('user', models.OneToOneField(help_text="Reference to Django's built-in User model", on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['rank'], name='user_profil_rank_eca27f_idx'), models.Index(fields=['unitname'], name='user_profil_unitnam_60f3e7_idx'), models.Index(fields=['status'], name='user_profil_status_6d69fb_idx'), models.Index(fields=['created_at'], name='user_profil_created_26443b_idx')],
            },
        ),
    ]
