# Generated by Django 5.2.5 on 2025-08-16 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_type', models.CharField(choices=[('instructions', 'Instructions'), ('offline', 'Offline'), ('downloads', 'Downloads'), ('publications', 'Publications')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file_url', models.URLField(blank=True, null=True)),
            ],
            options={
                'db_table': 'information_home_page',
            },
        ),
    ]
