# Generated by Django 5.2.5 on 2025-08-16 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_homepageinformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepageinformation',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='homepageinformation',
            name='file_url',
        ),
    ]
