version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '4200:4200'

  auth_service:
    build:
      context: ./services/auth_service
    env_file:
      - ./services/auth_service/.env
    ports:
      - '8000:8000'
    depends_on:
      - db

  sfd_service:
    build:
      context: ./services/SFD
    env_file:
      - ./services/SFD/.env
    ports:
      - '8001:8001'
    depends_on:
      - db

  gateway:
    build:
      context: ./gateway
    ports:
      - '80:80'
    depends_on:
      - frontend
      - auth_service
      - sfd_service

  db:
    image: postgres:18-alpine
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
